---
- name: copy splunkforwarder package to host
  aws_s3:
    bucket: "{{ s3_bucket_name }}"
    object: "{{ windows_binary }}"
    dest: "{{ windows_binary }}"
    mode: get
  delegate_to: localhost
  become: no
  vars:
    ansible_connection: local

- name: copy splunkforwarder package to target
  win_copy:
    src: "{{ windows_binary }}"
    dest: "{{ temp_directory }}\\{{ windows_binary }}"

- name: install splunkforwarder
  win_package:
    path: "{{ temp_directory }}\\{{ windows_binary }}"
    arguments: SET_ADMIN_USER=0 AGREETOLICENSE=yes /quiet
    state: present

- name: cleanup files
  win_file:
    path: "{{ temp_directory }}\\{{ windows_binary }}"
    state: absent