---
- name: find ec2 amis
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  vars:
    image_names:
      rhel-74: RHEL-7.4_HVM_GA-20170808-x86_64-2-Hourly2-GP2
      rhel-75: RHEL-7.5_HVM_GA-20180322-x86_64-1-Hourly2-GP2
      win-2016: Windows_Server-2016-English-Full-Base-2018.01.12
  roles:
    - ec2-find-amis

- name: provision linux ec2 instances
  hosts: localhost
  become: no
  vars:
    number_of_forwarders: 1
  vars_files:
    - splunk-nodes-ec2.yml
  pre_tasks:
    - name: generate nodes list
      set_fact:
        linux_generated_nodes: "{{ linux_generated_nodes|default([]) + linux_nodes }}"
      with_sequence: count="{{ number_of_forwarders }}"

    - debug:
        var: linux_generated_nodes
  roles:
    - role: ansible-role-ec2
      nodes: "{{ linux_generated_nodes }}"
      when: linux_generated_nodes is defined