- name: terminate ec2 instances
  hosts: localhost
  become: no
  tasks:
    - name: get ec2 instance information
      ec2_instance_facts:
        region: "{{ ec2_region }}"
        filters:
          vpc-id: "{{ ec2_vpc_id }}"
          "tag:app": splunk
          "tag:name": "{{ ec2_name_prefix }}-*"
      register: ec2_instances

    - name: terminate instances
      ec2:
        region: "{{ ec2_region }}"
        state: "absent"
        instance_ids: "{{ ec2_instances.instances | map(attribute='instance_id') | list }}"